{
	"id": "CVE-2018-10855",
	"vulnerabilities": [
		{
			"id": "CVE-2018-10855",
			"description": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
						"base_score": 5.9,
						"base_severity": "MEDIUM",
						"temporal_score": 5.9,
						"temporal_severity": "MEDIUM",
						"environmental_score": 5.9,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2018-10855"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHBA-2018:3788"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:1948"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:1949"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:2022"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:2079"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:2184"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:2585"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2019:0054"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2019/dsa-4396"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4072-1/"
				}
			],
			"published": "2018-07-03T01:29:00Z",
			"modified": "2024-05-14T06:19:28.098007Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.7",
			"vulnerable": true,
			"package": {
				"name": "ansible"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.4.6.0-r0"
					}
				],
				"fixed": [
					"2.4.6.0-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
