{
	"id": "CVE-2017-7478",
	"vulnerabilities": [
		{
			"id": "CVE-2017-7478",
			"description": "OpenVPN version 2.3.12 and newer is vulnerable to unauthenticated Denial of Service of server via received large control packet. Note that this issue is fixed in 2.3.15 and 2.4.2.",
			"severity": [
				{
					"type": "cvss_v30",
					"source": "security.alpinelinux.org",
					"cvss_v30": {
						"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"base_score": 7.5,
						"base_severity": "HIGH",
						"temporal_score": 7.5,
						"temporal_severity": "HIGH",
						"environmental_score": 7.5,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2017-7478"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securityfocus.com/bid/98444"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securitytracker.com/id/1038473"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.exploit-db.com/exploits/41993/"
				}
			],
			"published": "2017-05-15T18:29:00Z",
			"modified": "2023-11-29T06:22:23.082817Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.5",
			"vulnerable": true,
			"package": {
				"name": "openvpn"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.3.15-r0"
					}
				],
				"fixed": [
					"2.3.15-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.6",
			"vulnerable": true,
			"package": {
				"name": "openvpn"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.4.2-r0"
					}
				],
				"fixed": [
					"2.4.2-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
