{
	"id": "CVE-2020-9402",
	"vulnerabilities": [
		{
			"id": "CVE-2020-9402",
			"description": "Django 1.11 before 1.11.29, 2.2 before 2.2.11, and 3.0 before 3.0.4 allows SQL Injection if untrusted data is used as a tolerance parameter in GIS functions and aggregates on Oracle. By passing a suitably crafted tolerance to GIS functions and aggregates on Oracle, it was possible to break escaping and inject malicious SQL.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
						"base_score": 8.8,
						"base_severity": "HIGH",
						"temporal_score": 8.8,
						"temporal_severity": "HIGH",
						"environmental_score": 8.8,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-9402"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://docs.djangoproject.com/en/3.0/releases/security/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202004-17"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.netapp.com/advisory/ntap-20200327-0004/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2020/dsa-4705"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2022/05/msg00035.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://groups.google.com/forum/#%21topic/django-announce/fLUh_pOaKrY"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UZMN2NKAGTFE3YKMNM2JVJG7R2W7LLHY/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4296-1/"
				}
			],
			"published": "2020-03-05T15:15:12Z",
			"modified": "2024-06-04T05:27:57.016575Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r0"
					}
				],
				"fixed": [
					"1.11.29-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r0"
					}
				],
				"fixed": [
					"1.11.29-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r0"
					}
				],
				"fixed": [
					"1.11.29-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.8",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r0"
					}
				],
				"fixed": [
					"1.11.29-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r0"
					}
				],
				"fixed": [
					"1.11.29-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
