{
	"id": "CVE-2020-24583",
	"vulnerabilities": [
		{
			"id": "CVE-2020-24583",
			"description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
						"base_score": 7.5,
						"base_severity": "HIGH",
						"temporal_score": 7.5,
						"temporal_severity": "HIGH",
						"environmental_score": 7.5,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-24583"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://docs.djangoproject.com/en/dev/releases/security/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.netapp.com/advisory/ntap-20200918-0004/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.openwall.com/lists/oss-security/2020/09/01/2"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.oracle.com/security-alerts/cpujan2021.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://groups.google.com/forum/#%21topic/django-announce/Gdqn58RqIDM"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://groups.google.com/forum/#%21topic/django-announce/zFCMdgUnutU"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4479-1/"
				}
			],
			"published": "2020-09-01T13:15:11Z",
			"modified": "2024-05-14T08:01:22.439717Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r1"
					}
				],
				"fixed": [
					"1.11.29-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r1"
					}
				],
				"fixed": [
					"1.11.29-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r1"
					}
				],
				"fixed": [
					"1.11.29-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r1"
					}
				],
				"fixed": [
					"1.11.29-r1"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
