{
	"id": "CVE-2020-7471",
	"vulnerabilities": [
		{
			"id": "CVE-2020-7471",
			"description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
						"base_score": 9.8,
						"base_severity": "CRITICAL",
						"temporal_score": 9.8,
						"temporal_severity": "CRITICAL",
						"environmental_score": 9.8,
						"environmental_severity": "CRITICAL"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-7471"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://docs.djangoproject.com/en/3.0/releases/security/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202004-17"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.netapp.com/advisory/ntap-20200221-0006/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2020/dsa-4629"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.djangoproject.com/weblog/2020/feb/03/security-releases/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.openwall.com/lists/oss-security/2020/02/03/1"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.openwall.com/lists/oss-security/2020/02/03/1"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://groups.google.com/forum/#%21topic/django-announce/X45S86X5bZI"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://seclists.org/bugtraq/2020/Feb/30"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4264-1/"
				}
			],
			"published": "2020-02-03T12:15:26Z",
			"modified": "2023-12-06T01:00:38.606116Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.28-r0"
					}
				],
				"fixed": [
					"1.11.28-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.28-r0"
					}
				],
				"fixed": [
					"1.11.28-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.28-r0"
					}
				],
				"fixed": [
					"1.11.28-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.8",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.28-r0"
					}
				],
				"fixed": [
					"1.11.28-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.28-r0"
					}
				],
				"fixed": [
					"1.11.28-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
