{
	"id": "CVE-2021-25293",
	"vulnerabilities": [
		{
			"id": "CVE-2021-25293",
			"description": "An issue was discovered in Pillow before 8.1.1. There is an out-of-bounds read in SGIRleDecode.c.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"base_score": 7.5,
						"base_severity": "HIGH",
						"temporal_score": 7.5,
						"temporal_severity": "HIGH",
						"environmental_score": 7.5,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2021-25293"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202107-33"
				}
			],
			"published": "2021-03-19T04:15:13Z",
			"modified": "2024-05-14T08:28:24.530965Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.14",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.1.2-r0"
					}
				],
				"fixed": [
					"8.1.2-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.1.2-r0"
					}
				],
				"fixed": [
					"8.1.2-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
