{
	"id": "CVE-2021-28363",
	"vulnerabilities": [
		{
			"id": "CVE-2021-28363",
			"description": "The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
						"base_score": 6.5,
						"base_severity": "MEDIUM",
						"temporal_score": 6.5,
						"temporal_severity": "MEDIUM",
						"environmental_score": 6.5,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2021-28363"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202107-36"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202305-02"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/urllib3/urllib3/commits/main"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://pypi.org/project/urllib3/1.26.4/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4S65ZQVZ2ODGB52IC7VJDBUK4M5INCXL/"
				}
			],
			"published": "2021-03-15T18:15:19Z",
			"modified": "2024-05-22T17:24:38.922729Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.14",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.16",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.17",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.18",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.19",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.20",
			"vulnerable": true,
			"package": {
				"name": "py3-urllib3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.26.4-r0"
					}
				],
				"fixed": [
					"1.26.4-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
